name: Docker Container Health Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check-containers-health:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.24-dind
        options: --privileged
        ports:
          - 5432:5432
          - 6379:6379
          - 9092:9092
          - 7110:7110
          - 5245:80
          - 5272:80
          - 5167:80
          - 5151:80

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose curl

      - name: Build and start services
        run: docker-compose -f compose.yml up -d --build

      - name: Wait for services to be healthy
        run: |
          echo "Waiting for services to be healthy..."
          ATTEMPTS=0
          MAX_ATTEMPTS=20
          SLEEP=10

          while [ $ATTEMPTS -lt $MAX_ATTEMPTS ]; do
            UNHEALTHY=$(docker ps --filter "health=unhealthy" --format "{{.Names}}")
            STARTING=$(docker ps --filter "health=starting" --format "{{.Names}}")

            if [ -z "$UNHEALTHY" ] && [ -z "$STARTING" ]; then
              echo "All containers are healthy ✅"
              exit 0
            fi

            echo "Waiting... ($ATTEMPTS/$MAX_ATTEMPTS)"
            echo "Still starting: $STARTING"
            echo "Unhealthy: $UNHEALTHY"
            sleep $SLEEP
            ATTEMPTS=$((ATTEMPTS + 1))
          done

          echo "❌ Some containers failed to become healthy in time."
          docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"
          exit 1

      - name: Show container status
        run: docker ps -a

      - name: Show logs if failed
        if: failure()
        run: docker-compose logs
